language: node_js
install: "npm install; ./node_modules/.bin/cake install"
before_script: "./node_modules/.bin/cake compile"
script: "npm test"
node_js:
  - "0.8"
  - "0.10"
notifications:
  email:
    recipients:
      - contact@stevemcarthur.co.uk